name: Publish package to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: MontyD/package-json-updated-action@master
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v1
        if: steps.version-updated.outputs.has-updated
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        if: steps.version-updated.outputs.has-updated
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
        if: steps.version-updated.outputs.has-updated
      - run: yarn build
        if: steps.version-updated.outputs.has-updated
      - run: yarn publish --access=restricted
        if: steps.version-updated.outputs.has-updated
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}