name: Publish beta package to NPM

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          version-type: 'prerelease'
          preid: 'beta'
          tag-prefix: 'v'
          commit-message: '{{version}}'
      - run: yarn
      - run: yarn build
      - run: yarn publish --access=restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}